# Generated by Django 4.1.2 on 2022-10-10 18:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('code', models.UUIDField(default=uuid.UUID('3b187c26-5472-41fa-9687-7a87f7f4a1f5'), primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('code', models.UUIDField(default=uuid.UUID('3ce6ace1-48f2-4c50-bced-b7fd1a2ba909'), primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_number', models.IntegerField(blank=True, unique=True)),
                ('group', models.ManyToManyField(related_name='Person-Group+', to='Memory.group')),
            ],
        ),
    ]
