# Generated by Django 4.1.2 on 2022-10-09 22:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Memory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('code', models.UUIDField(default=uuid.UUID('b49c7f77-ec90-41ab-b6a1-8683d74aef18'), primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='group',
            name='id',
        ),
        migrations.AddField(
            model_name='group',
            name='code',
            field=models.UUIDField(default=uuid.UUID('d801274e-0fdc-4d8c-88f3-e43208080f85'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='code',
            field=models.UUIDField(default=uuid.UUID('dc3c05ad-7e85-4e49-b630-77244590559e'), primary_key=True, serialize=False),
        ),
    ]
